language: node_js
sudo: false
node_js:
  - "0.10.34"
  - "0.11.14"
before_install:
  - npm config set spin false
  - npm install -g npm@^2
  - npm install -g ember-cli
  - npm install -g sails
  - export PATH=$PATH:/home/travis/.nvm/v0.11.14/bin/:/home/travis/.nvm/v0.10.34/bin/
script: npm run-script test-all